'use client'

import Breadcrumb from '../../integrations/components/Breadcrumb'
import Recent from "../../components/Recent"
import { useRef, useState } from 'react'
import { PlayCircle, StopCircle } from 'lucide-react'

const recentData = [
    { name: "Code Generation", link: "/documentation/features/code-generation" },
    { name: "Edit Mode", link: "/documentation/features/edit" },
]

export default function CodeEditor() {

    const videoRef = useRef<HTMLVideoElement>(null)
    const [isPlaying, setIsPlaying] = useState(false)

    const handleTogglePlay = () => {
        if (!videoRef.current) return

        if (videoRef.current.paused) {
            videoRef.current.play()
            setIsPlaying(true)
        } else {
            videoRef.current.pause()
            setIsPlaying(false)
        }
    }


    return (
        <main className="space-y-6 text-gray-300">
            <Breadcrumb
                items={[
                    { label: "Home", href: "/documentation/home" },
                    { label: "Features", href: "/documentation/features" },
                    { label: "Code Editor", active: true },
                ]}
            />

            <h1 className="text-4xl sm:text-4xl font-medium text-white">Code Editor</h1>

            <p>
                View and edit your project’s code directly in Kavia.
            </p>

            <div className="shadow-2xl border border-gray-900 rounded-xl p-8 space-y-8">
                <div className='space-y-6'>
                    <p>
                        Kavia’s <strong>Code Mode</strong> gives you full access to your application’s underlying code through an integrated <strong>VS Code editor</strong>.
                        This provides a powerful, familiar environment for developers who want complete control over both frontend and backend logic.
                    </p>

                    <p>
                        Whether you need to customize components, write advanced logic, or integrate third-party services,
                        Code Mode empowers you to go beyond visual editing with precision and flexibility.
                    </p>

                    <div className="relative p-1 rounded-xl overflow-hidden border border-gray-800">
                        <video
                            ref={videoRef}
                            src="/images/features/codeeditor/vid1.mov"
                            width={800}
                            height={400}
                            className="w-full h-auto object-cover rounded-xl"
                            poster="/images/features/codeeditor/vid1.png"
                        />

                        <div className="absolute inset-0 flex items-center justify-center">
                            <button
                                onClick={handleTogglePlay}
                                className="flex items-center gap-2 bg-white text-gray-800 font-medium text-sm px-4 py-3 rounded-full shadow-2xl hover:bg-[#fff5f0] hover:text-[#f97316] transition-all duration-200"
                            >
                                 {isPlaying ? (
                                    <>
                                        <StopCircle className="w-6 h-6" />
                                        <span className="sm:inline hidden hover:underline">Stop Video</span>
                                    </>
                                ) : (
                                    <>
                                        <PlayCircle className="w-6 h-6" />
                                        <span className="sm:inline hidden hover:underline">Play Video</span>
                                    </>
                                )}
                            </button>
                        </div>
                    </div>

                    <h4 className="text-lg font-semibold text-white">Use Code Mode to:</h4>

                    <ul className="list-disc pl-6 space-y-2 text-gray-300">
                        <li>Review the structure and logic generated by Kavia</li>
                        <li>Make direct edits to frontend components and backend services</li>
                        <li>Add custom functions, APIs, or third-party integrations</li>
                        <li>Debug or fine-tune specific parts of your app manually</li>
                    </ul>

                    <p>
                        With the built-in <strong>VS Code interface</strong>, developers can enjoy syntax highlighting, file navigation, code formatting,
                        and more—making advanced custom development seamless within Kavia.
                    </p>

                    <p>
                        Kavia bridges the gap between low-code speed and full-code power,
                        letting you move effortlessly between AI-assisted workflows and professional-grade code editing.
                    </p>
                </div>
            </div>

            <Recent data={recentData} />
        </main>
    )
}